apiVersion: v1
kind: Namespace
metadata:
  name: minio-single-pod
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-dist
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-dist-w-repl
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minio-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "cms"